- src/simoc_sam/sensors/vernier.py
- src/simoc_sam/sensors/vernierCO2.py
- src/simoc_sam/sensors/vernierO2.py
This PR fixes the Vernier sensors finalization by calling `device.close()` on `exit`.
> Fix Vernier sensors finalization.

- src/simoc_sam/sensors/basesensor.py
- tests/test_basesensor.py
ID will be required for coordinating server actions. Ideally it will be implemented by the Sensor classes (device serial number for Vernier, USB port for others) but this will at least cover MockSensor.
> add random id to basesensor if not provided

- src/simoc_sam/sioserver.py
From https://python-socketio.readthedocs.io/en/latest/server.html#cross-origin-controls:
> * If an incoming HTTP or WebSocket request includes the Origin header, this header must match the scheme and host of the connection URL. In case of a mismatch, a 400 status code response is returned and the connection is rejected.
> * No restrictions are imposed on incoming requests that do not include the Origin header.
When using the dashboard -- served on `localhost:8080` -- the browser will include the `Origin` header and will specify `localhost:8080`, so this value must be explicitly accepted by the sioserver.  Currently the sioserver is serving on `localhost:8081`, so even though the host is the same, the port is different and using `8081` results in a dashboard error.
The problem does not …
> Fix CORS `allowed_origins` port.

- simoc-sam.py
- tmux.sh
This PR updates the `simoc-sam.py run-tmux` command to check if a session is already running and attach to it if it already is.  If no session is running it will start a new one as usual.
> Attach to existing tmux session if it is already running.

- config.cfg.tmpl
- src/simoc_sam/sioserver.py
This PR fixes two issues that prevented the server from running properly:
* `sioserver.py` is currently looking for `name` and `description` in the config, even though we settled on `name` and `desc`
* the `sensor_info`s use `sensor_name` and `sensor_desc`, so when comparing with those, the `sensor_` prefix is added
The logic also seems backward, since the `sensor_info` values take precedence over the config file, whereas it should be the opposite.  I'll fix this in a separate PR after some additional testing.
> Use correct var names when reading the config.

- src/simoc_sam/sensors/vernier.py
- src/simoc_sam/sensors/vernierWTHR.py
This PR adds support for the [Vernier Weather System](https://www.vernier.com/product/go-direct-weather-system/) sensor.
The code is mostly copy-pasted from the other two Vernier drivers.  At some point we should refactor it to remove duplication and possibly write a universal driver that will support all Vernier sensors.
> Add vernier-WTHR sensor driver.

- src/simoc_sam/sioserver.py
This should fix a somewhat rare issue that I've encountered:
https://github.com/overthesun/simoc-sam/blob/65156f94fa91bcf9ec63ba2d628beda54bd8789e/src/simoc_sam/sioserver.py#L181-L184
This piece of code executes `emit_readings` when the server starts, and `emit_readings` loops forever in a background task, sending readings to the clients:
https://github.com/overthesun/simoc-sam/blob/65156f94fa91bcf9ec63ba2d628beda54bd8789e/src/simoc_sam/sioserver.py#L150-L165
This in turn calls `emit_to_subscribers`, that sends the readings to each subscriber one by one:
https://github.com/overthesun/simoc-sam/blob/65156f94fa91bcf9ec63ba2d628beda54bd8789e/src/simoc_sam/sioserver.py#L113-L116
My understanding is that this background task is executed in a separate thread, but it's not thread safe.  If a new …
> Make `emit_readings()` more robust.

- src/simoc_sam/sioclient.py
- src/simoc_sam/sioserver.py
- tmux.sh
This PR improves the tmux layout to look like this:
The server (on the left) now only prints a message every few broadcasts, without printing the actual readings.  It also prints how many sensors/clients are connected.  On the right there is a panel for the sensors (during mission-1 there will only be Vernier sensors), one for the sioclient/csv logger, and a shell (useful for debugging).  These 3 panels are now wider so that more data fit in one line.
I also commented out a few more redundant messages.
> Improve tmux layout and message logging.

- src/simoc_sam/sensors/utils.py
- src/simoc_sam/sioserver.py
This PR recycles the sensor arg parser in order to read the `-d` option for the delay.  This can be refactored later to a better server-specific arg parser, but for now it's good enough and allows us to set the broadcast delay from the cmdline.  It also allows float delays (useful for testing).
Note that eventually we should create rooms where data are broadcasted at different intervals (possibly requested by the clients themselves), so that we could have e.g. the csv logger in the 1s room reading and logging all the data, but the dashboard in the 10s room getting a reading every 10s.
> Make server delay configurable.

- README.md
- hostinfo.py
- requirements.txt
- simoc-sam.py
This PR adds the `hostinfo.py` script and the `info`, `sensors-info`, `network-info` commands to `simoc-sam.py`.
The `hostinfo.py` can be run directly with `python3 hostinfo.py` (the `venv` must be active), or can be invoked using `python3 simoc-sam.py info`.
It will print something like:
```
===== Network info =====
Hostname: samrpi1
IP/MAC addresses:
* wlan0:
MAC : e4:5f:01:b5:73:90
IPv6: fe80::e65f:1ff:feb5:7390%wlan0
* bat0:
MAC : 42:3d:94:c7:3e:30
IPv4: 172.27.0.1
IPv6: fe80::403d:94ff:fec7:3e30%bat0
===== Sensors info =====
MCP2221 connected: True
Found 2 sensors:
* SGP30 (I2C addr: 0x58)
* SCD30 (I2C addr: 0x61)
```
In addition, the `network-info` and `sensors-info` commands have been added to `simoc-sam.py` to print only network or sensors information.
These commands will help …
> Add the hostinfo.py script and the `info` command to simoc-sam.py.

- README.md
- netinfo.py
- simoc-sam.py
This PR adds the `netinfo.py` script and the `hosts` command to `simoc-sam.py`.
The `netinfo.py` script can be run directly with `python3 netinfo.py`, or can be invoked using `python3 simoc-sam.py hosts`.
It will print something like:
```
Scanning <172.27.0.0/24> (might take a few seconds)...
+------------+---------------+--------+-----------+-------------------+
|     IP     |   Hostname    | Status | Interface |        MAC        |
+------------+---------------+--------+-----------+-------------------+
| 172.27.0.1 | samrpi1.local |   Up   |    ???    |        ???        |
| 172.27.0.2 | samrpi2.local |   Up   |   bat0    | 06:f3:3a:5d:37:21 |
| 172.27.0.3 | samrpi3.local |   Up   |   bat0    | aa:7c:0d:c9:b8:56 |
+------------+---------------+--------+-----------+-------------------+ …
```
> Add the netinfo.py script and the `hosts` command to simoc-sam.py.

- bash_aliases
This file contains aliases definition to make the use of `simoc-sam.py` and the RPi 0 in general simpler.
They can be installed by using `ln -s ~/simoc-sam/bash_aliases ~/.bash_aliases`.  `~/.bashrc` already looks for a `.bash_aliases` file and loads it automatically.  For some reason it already includes aliases for `ll`/`la`, but they are commented out.
> Add a `bash_aliases` file.

- src/simoc_sam/sensors/utils.py
This PR fixes a bug that occurs when trying to use `--no-sio`.  The check verifies that no `port` value is set when running with `--no-sio`, however the port has a default value which is always set, making the use of `--no-sio` impossible.
> Remove a conflicting argparse check.

- src/simoc_sam/sensors/scd30.py
The `sensors/scd30.py` sensor driver was missing this check and setting the MCP2221-related vars unconditionally.  This PR fixes that.
> Check for MCP2221 before setting envvars in the SCD30 driver.

- simoc-sam.py
This PR changes the behavior of the `copy-repo` command so that instead of copying the cwd, it always copies the root of the repo.  Note that `rsync` behavior changes depending on whether the source has a trailing `/` or not:
* without trailing `/` it copies the directory with all its content
* with a trailing `/` it only copies the content
Here we want to copy/update the content of the `simoc-sam` dir, hence the trailing `/`.
> Avoid using relative cwd in the copy-repo command.

- src/simoc_sam/sensors/bme688.py
- src/simoc_sam/sensors/scd30.py
- src/simoc_sam/sensors/sgp30.py
- src/simoc_sam/sensors/utils.py
This is a follow-up of:
* #48 
#48 requires https://github.com/adafruit/Adafruit_Blinka/pull/637 in order to work, so the `get_sensor_i2c_bus()` function can't be used unless we install `Adafruit_Blinka` from my fork.
> Revert I2C initialization to avoid `get_sensor_i2c_bus()`.

- src/simoc_sam/sensors/utils.py
This is in preparation of:
* #60 
It converts the `--no-sio` command line argument to `--sio`, so that by default sensors only print data.  If `--sio` (or later `--mqtt` are specified it will enable them.
> Replace the `--no-sio` option with `--sio`.

- bash_aliases
The `sam` alias defined in `bash_aliases` uses the `python` defined in the venv, whether that's necessary or not.  This works fine for most commands, except `create-venv`, since the venv's `python` is not available and the command fails.
This PR tries to use the `python` defined in the venv, and if it doesn't exist it falls back on the system `python`.
> Fallback on system `python` if the venv is missing.

- hostinfo.py
- requirements.txt
- src/simoc_sam/sensors/adafruit.py
- src/simoc_sam/sensors/sensors.toml
- src/simoc_sam/sensors/utils.py
This PR adds a new `sensors.toml` file that includes data about sensors, e.g.:
```toml
[scd30]
name = "SCD30"
description = "NDIR CO2, Temperature, and Humidity Sensor"
module = "simoc_sam.sensors.scd30"
i2c_address = 0x61
[scd30.data.CO2]
unit = "ppm"
label = "CO2 Concentration"
[scd30.data.temperature]
unit = "°C"
label = "Temperature"
[scd30.data.humidity]
unit = "%RH"
label = "Humidity"
```
It also includes a few utilities to access these info easily, and some code-refactoring to use them instead of hardcoded values.
> Add `sensors.toml` and refactor the code to use it

- src/simoc_sam/sensors/basesensor.py
Logging doesn't work if the dir is not there.  This PR adds a try/except that skips the logging if it's missing.
> Skip logging if the dir is not there.

- simoc-sam.py
This PR fixes a bug introduced in #99, where the `@needs_root` decorator was being executed at function declaration and not at function call time.
> Fix @needs_run to check on function calls.

- requirements.txt
- src/simoc_sam/sensors/sensors.toml
- src/simoc_sam/sensors/tsl2591.py
This PR adds the driver for the [TSL2591 sensor](https://www.adafruit.com/product/1980).
The sensor exposes 3 readings:
* light (lux)
* visible (as a 32 bit int between 0-2147483647)
* infrared (as a 16 bit int between 0-65535)
This is a trimmed list with some sample readings and added inline comments that I just took in a dark room, only lit by a computer screen:
```py
$ python -m simoc_sam.sensors.tsl2591 -v -d1
[TSL2591] Light: 1.0lux: Visible: 196616: Infrared: 3
[TSL2591] Light: 1.2lux: Visible: 196616: Infrared: 3
[TSL2591] Light: 2.0lux: Visible: 196623: Infrared: 3
[TSL2591] Light: 2.1lux: Visible: 196623: Infrared: 3
[TSL2591] Light: 10.4lux: Visible: 1048650: Infrared: 16
[TSL2591] Light: 10.4lux: Visible: 1048650: Infrared: 16
[TSL2591] Light: 1.0lux: Visible: 196616: Infrared: …
```
> Add driver for the TSL2591 sensor

- requirements.txt
- src/simoc_sam/sensors/sensors.toml
- src/simoc_sam/sensors/veml7700.py
This PR adds the driver for the [VEML7700 sensor](https://www.adafruit.com/product/4162) (they also have a [right angle version](https://www.adafruit.com/product/5378) -- the driver should work with both).
The sensor exposes a single reading: light (in lux).
This is a trimmed list with some sample readings and added inline comments that I just took in a dark room, only lit by a computer screen:
```python
$ python -m simoc_sam.sensors.veml7700 -v -d1
[VEML7700] Light: 3lux
[VEML7700] Light: 3lux
[VEML7700] Light: 3lux
[VEML7700] Light: 7lux
[VEML7700] Light: 7lux
[VEML7700] Light: 7lux
[VEML7700] Light: 31lux
[VEML7700] Light: 31lux
[VEML7700] Light: 31lux
[VEML7700] Light: 3lux
[VEML7700] Light: 3lux
[VEML7700] Light: 3lux
[VEML7700] Light: 263lux
[VEML7700] Light: 2781lux
[VEML7700] …
```
> Add driver for the VEML7700 sensor

- tmux/mqtt.sh
Due to hardware problems with the SGP30 sensors we got from Adafruit, we had to remove them from the sensor array.  This PR updates `mqtt.sh` (used to launch `tmux`) to remove the SGP30 pane.
According to https://forums.adafruit.com/viewtopic.php?t=212812 they fixed the issue, so if/when we get replacements and add the sensors back to the array we can revert this commit to get the pane back.
> Remove the SGP30 from `mqtt.sh`

- tmux/mqtt.sh
Activating the venv in the `mqtt.sh` script doesn't seem to work, and the venv needs to be activated again for each pane, so I removed and also updated the cwd to ensure it's activated from the right dir.
> Remove venv activation from `tmux/mqtt.sh`

- configs/README.md
- configs/sensor-runner@.service
This is an alternative solution to:
* #110 
Instead of trying to launch `tmux` as a service, I created a unit file template that can be used to launch the individual sensor scripts as services, that can be enabled to automatically start on boot.  The logs can be inspected using e.g. `journalctl -u sensor-runner@scd30.service -f`, so technically a `tmux` script that launches `journalctl` could be created to inspect multiple logs at once.  This PR doesn't include this, and also doesn't include automation to (un)symlink this file.  This can be added in a separate PR.
> Add a systemd unit file to run sensors as services

- simoc-sam.py
This solves a few Python 3.12 warnings:
```py
simoc-sam/simoc-sam.py:98: SyntaxWarning: invalid escape sequence '\d'
ipv4_re = re.compile('^\d+\.\d+\.\d+\.\d+$')  # does it look like an IPv4?
simoc-sam/simoc-sam.py:139: SyntaxWarning: invalid escape sequence '\d'
host_re = re.compile('^samrpi(\d+)$')
simoc-sam/simoc-sam.py:140: SyntaxWarning: invalid escape sequence '\s'
address_re = re.compile('^(\s*address\s+)((\d+\.\d+.\d+.)(\d+))(\s*)$')
```
> Use raw strings for regex patterns in simoc-sam.py.

- simoc-sam.py
This fixes #108 by using `execvp` to re-run the command as root when the command is decorated with the `@needs_root` decorator.  This means that the `sam` alias can be used directly without `sudo`, which is invoked when needed by `@needs_root`/`execvp`.
> Use `execvp` in `needs_root` to re-run the command as root

- .github/dependabot.yml
This PR is a follow-up of:
* #123 
and it enables dependabot for this repo in order to keep deps updated.
> Enable dependabot for this repo

- simoc-sam.py
This `simoc-sam.py` installs the [GeeekPi 3.5" touchscreen for the Raspberry Pi 4/5](https://www.amazon.com/dp/B0D7VDWBBC).
In order to do that it will:
* clone https://github.com/goodtft/LCD-show.git
* make the whole repo executable (a bit sketchy, but the instructions says to do it)
* run the [`MHS35-show`](https://github.com/goodtft/LCD-show/blob/master/MHS35-show) script (that does more sketchy things to install the screen)
* schedule the repo to be deleted on boot (since the scripts reboots the Pi before `simoc-sam.py` does it)
This is currently untested, but will test it and report back shortly.
> Add a command to install the touchscreen.

- simoc-sam.py
This PR adds an `initial-setup` command to `simoc-sam.py` that:
* installs the `.bash_aliases` (fixes #96)
* removes default home directories (`Documents`, `Pictures`, `Videos`, etc.)
* updates the system and installs missing dependencies (see #65 and #95)
In the future we can expand this command to do additional things (such as updating `/etc/hosts`).
> Add an `initial-setup` command to `simoc-sam.py`

- simoc-sam.py
This is a follow-up of:
* #130 
Instead of using the default 480x320 resolution (which is quite cramped), it doubles it to 960x320.  Even though the screen only has 480x320 pixels, the image is then downscaled automatically but looks fine, and the screen can still fit 4 times more things.
We could also add a command to change the resolution that calls e.g. `fbset -xres 960 -yres 640`, but so far it doesn't seem particularly useful.
> Set 960x640 as default res for the 3.5" screen

- requirements.txt
`Adafruit-Blinka` 8.57.0 doesn't work on the RPi 0s, so revert back to 8.56.0.
Adafruit is working on it, but as of 8.60.3 the issue is still not fixed.
> Temporary revert Adafruit-Blinka to 8.56.0

- hostinfo.py
- simoc-sam.py
This PR adds a `services-info` command that:
* prints a list of relevant running services and whether they are active or not, enabled or not, have errors or not;
* prints a list of relevant services that are not running;
* prints a list of commands that can be used to investigate errors, if any;
Relevant services include all services defined by SIMOC Live itself (stored in the `configs` dir) and some system services that are needed to run SIMOC Live.
A couple of examples of the output:
```
===== Services info =====
Service name              | Active         | Enabled    | Errors
--------------------------+----------------+------------+--------
avahi-daemon              | 🟢active       | 🟢enabled  | 
systemd-timesyncd         | 🟢active       | 🟢enabled  | …
```
> Add the `services-info` command to `simoc-sam.py`

- src/simoc_sam/siobridge.py
This PR updates the code in `siobridge.py` to automatically find all IPs and hostname that point to the local host and add them to the `allowed_origins`.  This will allow anyone in the same private networks of the host running the `siobridge` and SIMOC Web to access the web interface regardless of the network they are in.
> Generate the list of CORS allowed origins dynamically

- tmux/mqtt.sh
- tmux/sensors.sh
This PR adds a new tmux script that opens for panes and runs the 3 standard sensors (SCD30, BME688, SGP30) + a 4th empty pane (for debugging, etc.).
> Add a tmux script for the sensors

- configs/sensor-runner@.service
- simoc-sam.py
This PR fixes a bug that prevented the services to automatically restart on boot.
Before, the `setup_systemd_service` did the following things:
1. create a symlink pointing to the unit (template) file
2. check if the service was enabled and, if not, enable it
3. check if the service was active and, if not, start it
During 1., a symlink in `/etc/systemd/system` was manually created, however this is apparently enough to enable the service (`is-enabled` returned `true`).  Because of this, during 2., the service was not enabled.  Enabling the service creates another symlink in `/etc/systemd/system/multi-user.target.wants/` which is responsible for starting the service on boot, but since the `enable` command was skipped, this was not happening.  Since both `enable` and `start` are idempotent …
> Fix systemd services not restarting on boot

- src/simoc_sam/defaults.py
- src/simoc_sam/sensors/basesensor.py
- src/simoc_sam/sensors/utils.py
- tests/test_basesensor.py
- tests/test_config.py
This PR moves the jsonl logging from the `MQTTWrapper` to the `BaseSensor` class.
Fixes #221.
> Move logging from `MQTTWrapper` to `BaseSensor`

- simoc-sam.py
The `HOME` env var is used by `Path.home()` to find files such as the user config introduced in #214.  Some `simoc-sam.py` commands are decorated with `@needs_root`, that run the command with `sudo`.  Running commands with `sudo` changes the current user, which changes the value of `HOME` and affects the result of `Path.home()`.  This PR fixes `@needs_root` to preserve the original `HOME`.
> Preserve HOME envvar while running as sudo

- simoc-sam.py
This PR introduces the following improvements to the `sam update` command:
* The command now updates the current branch, even if it's not `master`;
* The command now works regardless of the current cwd;
> Update the `sam update` command to update the current branch
