overthesun/simoc-sam

README.md, src/simoc_sam/sensor_manager.py, src/simoc_sam/sensors/basesensor.py, src/simoc_sam/sensors/utils.py, src/simoc_sam/sensors/vernier_utils.py, src/simoc_sam/sioclient.py, src/simoc_sam/sioserver.py, tests/test_basesensor.py, tmux.sh
This envvar allows you to specify the host and port of the server as `host:port`.  It defaults to `localhost:8081`.
=> Add support for a `SIOSERVER_ADDR` envvar.

src/simoc_sam/sensors/utils.py, src/simoc_sam/sensors/vernier_utils.py, src/simoc_sam/sioserver.py
Should be tested with the Vernier sensor
=> move config parsing to server

requirements.txt, src/simoc_sam/sensors/bme688.py
This PR adds the BME-688 driver written by @GregRRoss, with some tweaks on top.
Fixes https://github.com/overthesun/simoc-sam/issues/10.
=> BME-688 driver

index.html, src/simoc_sam/sioserver.py
This PR fixes and improves `index.html`.
=> Fix and improve index.html

simoc-sam.py
This command uses `rsync` to copy the repository to a different host.
This will be useful to update the other RPis in the mesh network with no internet access.
It might be better to exclude the `venv` dir, but for now I'm copying everything.
=> Add the `copy-repo` command.

hostinfo.py, netinfo.py, simoc-sam.py
This is a follow-up of:
* #61 
* #62 
It fixes a few minor issues and introduces some improvements.
=> Fix and improve `simoc-sam.py`-related functions

simoc-sam.py
This command checks that the IP address of the `bat0` interface (e.g. `172.27.0.5`) matches the hostname (e.g. `samrpi5`).
If they don't match, it will update the IP in the `/etc/network/interfaces.d/bat0` file and restart the RPi.
This command is also meant to be run on boot by adding `python3 /home/pi/simoc-sam/simoc-sam.py fix-ip` to `/etc/rc.local`, for two reasons:
* all images are flashed with the same IP, but with the correct hostname (it can be set from the Imager), so the IP needs to be updated on the first boot;
* for all subsequent boots, the IP should be correct, so this command won't change anything, but it will help ensuring that the IP is still set correctly.
Eventually the `start-batman-adv.sh` script could be merged/combined with this command too.
=> Add the `fix-ip` command.

src/simoc_sam/sensors/adafruit.py, src/simoc_sam/sensors/bme688.py, src/simoc_sam/sensors/scd30.py, src/simoc_sam/sensors/sgp30.py, src/simoc_sam/sensors/utils.py, tmux.sh
This PR adds a script to automatically find and launch connected Adafruit sensors.
=> Add a script to find and launch Adafruit sensors.

hostinfo.py, requirements.txt, src/simoc_sam/sensors/basesensor.py, src/simoc_sam/sensors/scd30.py, src/simoc_sam/sensors/scd4x.py
This PR adds the driver for the SCD-4X sensor.  Most of the code was written by @fcarbogn.
=> Add driver for the SCD-4X sensor

src/simoc_sam/sensors/basesensor.py, src/simoc_sam/sensors/bme688.py, src/simoc_sam/sensors/scd30.py, src/simoc_sam/sensors/scd4x.py, src/simoc_sam/sensors/sensors.toml, src/simoc_sam/sensors/sgp30.py, src/simoc_sam/sensors/utils.py, tests/test_basesensor.py
This PR refactors the sensor drivers:
* update `sensors.toml`
* removes hardcoded sensor information from the drivers
* refactors and simplifies drivers' `import`s
* adds a couple of methods to `BaseSensor` to remove duplication
=> Refactor sensor drivers

src/simoc_sam/sensors/sgp30.py
This PR fixes a couple of typos in the SGP30 driver.
=> Fix typos in the SGP30 driver

simoc-sam.py
Exclude the `venv` and `.git` dirs by default from the `copy-repo` command, and add two new commands to explicitly include them.
=> Add the `copy-repo-venv` and `copy-repo-git` commands

src/simoc_sam/sensors/basesensor.py
This PR adds basic local logging.  For every reading published on MQTT, each RPi 0 will also log the message on a file.
=> Implement basic local logging

src/simoc_sam/mqttbridge.py, src/simoc_sam/sensors/utils.py, tests/test_utils.py
=> Replace `samrpi` with `sambridge`

tmux/mqtt.sh
The automatic activation doesn't seem to work, so activate the tmux manually for each pane.
=> Manually activate MQTT tmux.

src/simoc_sam/sensors/basesensor.py
This handles a `RuntimeError` that might pop up while reading data.
=> Handle RuntimeErrors while reading data.

src/simoc_sam/mqttbridge.py, src/simoc_sam/sensors/utils.py
This will allow us to subscribe to different topics from the mqtt bridge.
=> Add a --mqtt-topic arg.

src/simoc_sam/sensors/mocksensor.py, src/simoc_sam/sensors/sensors.toml
The mock sensor broke in #76 since it wasn't added to `sensors.toml`.  This PR fixes that, adds more values (altitude and pressure) and refactors the code to be simpler and more realistic.
=> Fix, improve, and refactor the mock sensor

configs/nmconnection.tmpl, simoc-sam.py
This PR automates the set up of a connection to an existing WiFi network.
=> Add a `simoc-sam.py` command to connect to a WiFi network.

simoc-sam.py
This is a follow-up of:
* #79 
* #118
It adds the commands `setup-mqttbridge` and `teardown-mqttbridge` that symlink/enable/start (and unlink/disable/stop) the `mqttbridge` script.
=> Add the `setup/teardown-mqttbridge` commands.

dev-requirements.txt, requirements.txt
This PR pins the dependencies.
=> Pin dependencies

src/simoc_sam/sensors/sensors.toml
This PR:
* adds two missing modules
* fixes a label
* removes an extra space
=> Update modules in sensors.toml
